[build]
publish = "public"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/webhooks/slack-events"
to = "/.netlify/functions/slack-events"
status = 200

[[redirects]]
from = "/webhooks/slack-commands"
to = "/.netlify/functions/slack-commands"
status = 200

[[redirects]]
from = "/badge"
to = "/.netlify/functions/badge"
status = 200

[template.environment]
SLACK_BOT_TOKEN = "Slack App Bot Token"
SLACK_SIGNING_SECRET = "Slack App Signing Secret"
